### ISSUE TITLE
Processing >10k trajectories

### ISSUE THREAD

**Issue by antanij** [alecheckert/saspt#4]
This may be an FAQ: the code seems to be processing only 10000 trajectories even if the input dataset contains many more. Are these the first 10,000 trajectories in the input array or randomly chosen? Is there a variable to change this?  

Kudos on the great paper and the public repo!

**Comment by alecheckert** [comment]
They're randomly chosen; that behavior exists to put a cap on computation time when running on large datasets. It can be changed with the `sample_size` parameter to `StateArrayParameters` (default 10000).

For instance, in the [example](https://github.com/alecheckert/saspt/blob/main/examples/examples.py#L20) you could specify `sample_size` in the `settings` dict to change that number.

and thanks for pointing this out! I'd prefer to leave the issue open so it reminds me to add a note to the example and the docs.

**Comment by antanij** [comment]
Great! Thanks :)
