### ISSUE TITLE
Can the code be used for long trajectories?

### ISSUE THREAD

**Issue by antanij** [alecheckert/saspt#5]
Possibly another FAQ, more on the scientific side rather than the repo. I am asking to make sure because of fast response (thanks again)!

Since the number of jumps for each trajectory are accounted for in the calculation ([alpha_j has a factor of n_i](https://saspt.readthedocs.io/en/latest/model.html#state-arrays)), my intuition is that the code can be safely used even for non-blinking fluorophores which would end up with loooooong trajectories.

Is that correct?

**Comment by alecheckert** [comment]
Yes exactly - it's really the number of _jumps_ that determines state occupations, not the number of trajectories. At least for 2D tracking with short focal depth - fast particles tend to move in and out of the focus quickly, leaving many short trajectories, while slow particles tend to stay in the focus, leaving a few long trajectories. So as you alluded, the number of jumps in each state is a better predictor of the total amount of that state than the number of trajectories.

We've used `saspt` with non-blinking fluorophores; the main challenge with those experiments was keeping the particle density low enough for accurate tracking, but provided that the tracking is good, there's nothing intrinsically different about the parameters/analysis.
