### ISSUE TITLE
Does the code output posterior diffusion coefficient probability for every transition?

### ISSUE THREAD

**Issue by antanij** [alecheckert/saspt#6]
Hi again @alecheckert,

I am wondering if one can access a diffusion coefficient value for every frame-to-frame transition during a trajectory. So a trajectory with length of N frames will have N-1 diffusion coefficient values.

Does saspt report that or carry out that kind of assignment at all?

The natural guess would be `SA.trajectories.something` which would be a row or column vector of length N-1. But I could not find something like that. Am I thinking in the right direction?

**Comment by antanij** [comment]
@alecheckert reminder about this.

**Comment by alecheckert** [comment]
Thanks for the nudge; sorry for the delay in response!

saspt doesn't infer state transitions - what is does is split the trajectories into smaller fragments of size `splitsize` (default 10 jumps) and infer separate distributions over the diffusion coefficient for each fragment. This helps to regularize the inference problem and prevent tracking errors from influencing the result too much (especially useful for dense tracking). Those are accessible via the `StateArray.posterior_assignment_probabilities` attribute. Happy to send an example if it helps.

You could make `splitsize` smaller to get more fine-grained temporal resolution, but at the cost of statistical resolution (inability to separate populations).
